name: Deploy PHP App to FTP Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate deploy.json
      run: |
        COMMIT_ID="${{ github.sha }}"
        TIMESTAMP="$(git log -1 --pretty=%cI)"  
        COMMIT_MESSAGE="$(git log -1 --pretty=%s | jq -Rs .)"  # Escapa el mensaje correctamente para JSON

        echo '{' > deploy.json
        echo '  "commit": "'$COMMIT_ID'",' >> deploy.json
        echo '  "message": '$COMMIT_MESSAGE',' >> deploy.json  # Sin comillas dobles adicionales
        echo '  "date": "'$TIMESTAMP'"' >> deploy.json  # Cierre correcto de comillas
        echo '}' >> deploy.json

        cat deploy.json  # Muestra el contenido en la consola

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: clientes.tecnoactive.cl
        username: ${{ secrets.FTPUSERNAME }}
        password: ${{ secrets.FTPPASSWORD }}
        protocol: ftps
        server-dir: public_html/liftandlearn-app/
        local-dir: ./
